config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'cv' => "pages#cv"

  get 'technologies' => "pages#technologies"

  get 'contact' => "pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def cv
  end

  def technologies
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<!-- <nav class="navbar navbar-default">
  <div class="container-fluid">
   
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

   
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "CV", cv_path %></li>
        <li><%= link_to "Technologies", technologies_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        
      </ul>
      
      
    </div>
  </div>
</nav>

<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <p>Site built by <%= link_to "Mónica Seco", 'https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile' %> @2015</p>
  </div>
</nav> -->

<div id="section-topbar">
    <div id="topbar-inner">
      <div class="container">
        <div class="row">
          <div class="dropdown">
            <ul id="nav" class="nav">
              <li class="menu-item"><a class="smoothScroll" href="#about" title="About"><i class="icon-user"></i></a></li>
              <li class="menu-item"><a class="smoothScroll" href="#resume" title="Resume"><i class="icon-file"></i></a></li>
              <li class="menu-item"><a class="smoothScroll" href="#work" title="Works"><i class="icon-briefcase"></i></a></li>
              <li class="menu-item"><a class="smoothScroll" href="#contact" title="Contact"><i class="icon-envelope"></i></a></li>
            </ul><!--/ uL#nav -->
          </div><!-- /.dropdown -->
          <div class="clear"></div>
        </div><!--/.row -->
      </div><!--/.container -->

      <div class="clear"></div>
    </div><!--/ #topbar-inner -->
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mónica Seco</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>
<body data-spy="scroll" data-offset="0" data-target="#nav">
<%= render "layouts/header" %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!-- <div class="container">
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>Please consult this website to see how a chemical engineer is using Ruby On Rails for the first time.</p>
  <p> Notice that I am in professional conversion into the IT domain.To do that I am signed in <%= link_to "Stuk", 'https://stuk.io/en' %> and <%= link_to "Codecademy", 'http://www.codecademy.com/' %>.</p>
  	<p>By exploring this website you will be able to find my professional course. </p>
  	<h3> Contact me if you are interested to hire me!</h3>
</div>
</div> -->

<div id="headerwrap">
	<section id="about" name="about"></section>
		<div class="container">
			<div class="row centered">
				<div class="col-lg-12">
					<h1>Mónica Seco</h1>
					<h3>Web Designer | Ruby on Rails Developer | Chemical Engineer</h3>
				</div><!--/.col-lg-12 -->
			</div><!--/.row -->
		</div><!--/.container -->
	</div>

	<div id="intro">
		<div class="container">
			<div class="row">
				
				<div class="col-lg-2 col-lg-offset-1">
					<h5>ABOUT</h5>
				</div>
				<div class="col-lg-6">
					<p align="justify"> My name is Mónica Seco. I am a self-taught designer & developer focused on HTML/CSS and Ruby On Rails.
						I am trying to convert myself professionally from Chemical Engineering to the IT domain.
						In 2014 I decided to sign in <%= link_to "Codecademy", 'http://www.codecademy.com/' %> and <%= link_to "Stuk.io", 'https://stuk.io/en' %> in order to learn more about web development.</p>
					<p align="justify">This site was built using what I have acquired during my learning process (Ruby-On-Rails, HTML, CSS, Bootstrap, jQuery, GitHub and Heroku).</p>
					
					<h1 class="text-center" style="color:white; text-transform:uppercase">Looking for a first professional experience!</h1>
				</div>
				
				
			</div><!--/.row -->
		</div><!--/.container -->
	</div>

	<section id="resume" name="resume"></section>
	<div class="container desc">
		<div class="row">

				<div class="col-lg-2 col-lg-offset-1">
					<h5>EDUCATION</h5>
				</div>
				<div class="col-lg-6">
					<p><t>Chemical Engineering</t><br>
					Superior Institut of Engineering of Coimbra (<%= link_to "ISEC", 'http://www.isec.pt/default.aspx' %>)<br>
					Coimbra, Portugal<br></p>
					
					<i>Bachelor's Degree</i>
					
				</div>
				<div class="col-lg-3">
					<p><sm>GRADUATED IN DECEMBER 2009</sm><br></p>
				</div>
	
		</div><!--/.row -->
		<br>
		<hr>
		<div class="col-lg-2 col-lg-offset-1">
					<h5>ADDTIONAL TRAINING</h5>
				</div>
				<div class="col-lg-6">
					<p><t>HTML/CSS</t><br>
						<%= link_to "Codecademy", 'http://www.codecademy.com/tracks/web' %><br>
						<i>Learned how to create websites by structuring and styling pages with HTML and CSS.</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>2014</sm><br></p>
				</div>
				<div class="col-lg-6 col-lg-offset-3">
					<p><t>JavaScript</t><br>
						<%= link_to "Codecademy", 'http://www.codecademy.com/tracks/javascript' %><br>
						<i>Learned the fundamentals of JavaScript.</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>2014</sm><br></p>
				</div>
				<div class="col-lg-6 col-lg-offset-3">
					<p><t>jQuery</t><br>
						<%= link_to "Codecademy", 'http://www.codecademy.com/tracks/jquery' %><br>
						<i>Learned how to make interactive websites and create animations.</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>2014</sm><br></p>
				</div>
				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Ruby On Rails</t><br>
						<%= link_to "Stuk.io", 'https://stuk.io/en/courses/ruby-on-rails-fundamentals' %><br>
						<i>Learned the Ruby On Rails Fundamentals.</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>2015</sm><br></p>
				</div>

				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Ruby On Rails</t><br>
						<%= link_to "Stuk.io", 'https://stuk.io/en/courses/2-sided-marketplace' %><br>
						<i>Learned how to build a marketplace using Ruby on Rails</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>2015</sm><br></p>
					</p>
				</div>

				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Ruby On Rails</t><br>
						<%= link_to "Stuk.io", 'https://stuk.io/en/courses/social-network' %><br>
						<i>Learned how to build a social network using Ruby on Rails</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>2015</sm><br></p>
				</div>

				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Ruby On Rails</t><br>
						<%= link_to "Stuk.io", 'https://stuk.io/en/courses/directory-website' %><br>
						<i>Learned how to build an online review and directory website using Ruby on Rails</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>2015</sm><br></p>
				</div>

				<div class="col-lg-6 col-lg-offset-3">
					<p><t>Ruby On Rails</t><br>
						<%= link_to "Stuk.io", 'https://stuk.io/en/courses/dating-app' %><br>
						<i>Learning how to build a dating app using Ruby on Rails</i>
					</p>
				</div>
				<div class="col-lg-3">
					<p><sm>IN PROGRESS</sm><br></p> 
				</div>
		</div>
	<div id="skillswrap">
		<div class="container">
			<div class="row">
					<div class="col-lg-2 col-lg-offset-1">
						<h5>SKILLS</h5>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="javascript" height="130" width="130" style="width: 130px; height: 130px;"></canvas>
						<p>HTML/CSS</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 60,
										color:"#1abc9c"
									},
									{
										value : 30,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("javascript").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="bootstrap" height="130" width="130" style="width: 130px; height: 130px;"></canvas>
						<p>Bootstrap</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 50,
										color:"#1abc9c"
									},
									{
										value : 50,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("bootstrap").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="wordpress" height="130" width="130" style="width: 130px; height: 130px;"></canvas>
						<p>JavaScript</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 30,
										color:"#1abc9c"
									},
									{
										value : 70,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("wordpress").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					
					<div class="col-lg-3 col-lg-offset-3 centered">
						<canvas id="html" height="130" width="130" style="width: 130px; height: 130px;"></canvas>
						<p>jQuery</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 40,
										color:"#1abc9c"
									},
									{
										value : 60,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("html").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="photoshop" height="130" width="130" style="width: 130px; height: 130px;"></canvas>
						<p>Ruby On Rails</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 70,
										color:"#1abc9c"
									},
									{
										value : 30,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("photoshop").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>

					<div class="col-lg-3 centered">
						<canvas id="illustrator" height="130" width="130" style="width: 130px; height: 130px;"></canvas>
						<p>Git</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 25,
										color:"#1abc9c"
									},
									{
										value : 75,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("illustrator").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					
			</div><!--/.row -->
			<br>
		</div><!--/.container -->
	</div>

	<section id="work" name="work"></section>
	<div class="container desc">
		<div class="row">
				<div class="col-lg-2 col-lg-offset-1">
					<h4><strong>To Do List</strong></h4>
				</div>

				<div class="col-lg-6 col-lg-offset-1">
					<p><i>This application was built during my training on the Stuk.io platform. It was developed using the Ruby On Rails framework and deployed using the <%= link_to "Heroku", 'https://www.heroku.com/' %> cloud.</i></p>
				</div>

				<div class="image_stukdo">					
					<p><%= link_to image_tag("Mpage_stukdo.png",:style => "width:600px;display: block; margin: 0 auto;"), 'http://desolate-castle-3365.herokuapp.com/' %></p>
					<h6 class="text-center">Used gems: 'twitter-bootstrap-rails', 'font-awesome-rails', 'simple_form', 'devise','auto_html','rails_12factor' and 'pg'</h6>
				</div>
		<br/>
				<div class="col-lg-6 col-lg-offset-3">
					<p>Try this application by using the credentials below.<br/>
					<strong>User:</strong><i> teste@teste.com</i><br/>
					<strong>Password:</strong><i> 1234567890</i></p>
				</div>		

				
		
		</div><!--/.row -->
		<br>
		<br>

		<div class="row">
			<div class="col-lg-2 col-lg-offset-1">
					<h4><strong>Market Place</strong></h4>
				</div>

				<div class="col-lg-6 col-lg-offset-1">
					<p><i>Based on the Ruby On Rails framework and deployed using the <%= link_to "Heroku", 'https://www.heroku.com/' %> cloud, this application was built during my training on the Stuk.io platform. It as the purpose of simulating a digital book store.</i></p>
				</div>

				<div class="image_estuk">					
					<p><%= link_to image_tag("Mpage_estuk.png",:style => "width:600px;display: block; margin: 0 auto;"), 'http://infinite-basin-7580.herokuapp.com//' %></p>
					<h6 class="text-center">Used gems: 'twitter-bootstrap-rails', 'simple_form', 'devise','cancan','paperclip', 'dotenv-rails', 'aws-sdk', 'friendly_id', 'stripe', 'aasm', rails_12factor' and 'pg'</h6>
				</div>
		<br/>
				<div class="col-lg-6 col-lg-offset-3">
					<p>Try this application by using the credentials below.<br/>
					<strong>User:</strong><i> teste@teste.com</i><br/>
					<strong>Password:</strong><i> 1234567890</i></p>
				</div>		
		</div><!--/.row -->
	</div>

	<section id="contact" name="contact"></section>
<div id="footwrap">
		<div class="container">
			<div class="row">
			
				<div class="col-lg-2 col-lg-offset-1">
					<h5>CONTACT</h5>
				</div>
				<div class="col-lg-6">
					<p><t>Email</t><br>
						seco.monica@outlook.com <br>
					</p>
					
				</div>
				<div class="col-lg-3">
					<p><sm>SOCIAL LINKS</sm></p>
					<p>						
						<%= link_to '<i class="icon-linkedin"></i>'.html_safe, "http://www.linkedin.com/in/monicaseco" %>
					</p>
					<p>
						<%= link_to '<i class="icon-github"></i>'.html_safe, "http://github.com/monicaseco" %>
					</p>
				</div>
			</div><!--/.row -->
		</div><!--/.container -->

	</div>

	<div id="c">
		<div class="container">
			<p>Created by <strong>Mónica Seco</strong> @2015</p>
		</div>
	</div>